- name: apps:guide
  color: fbca04
- name: apps:website
  color: fbca04
- name: blocked
  description: Generic label to stop Kodiak from merging a pull request.
  color: fc1423
- name: bug
  description: Something is not working as expected.
  color: '000000'
- name: discord
  description: This is a Discord-related issue.
  color: 5865f2
- name: duplicate
  color: cfd3d7
- name: feature request
  color: fcf95a
- name: good first issue
  color: 7057ff
- name: help wanted
  color: '008672'
- name: in review
  description: This pull request is currently in review; halts Kodiak.
  color: aed5fc
- name: invalid
  description: This is not related to discord.js.
  color: e4e669
- name: need reproduction
  color: c66037
- name: packages:api-extractor
  color: fbca04
- name: packages:api-extractor-model
  color: fbca04
- name: packages:brokers
  color: fbca04
- name: packages:builders
  color: fbca04
- name: packages:collection
  color: fbca04
- name: packages:core
  color: fbca04
- name: packages:create-discord-bot
  color: fbca04
- name: packages:discord.js
  color: fbca04
- name: packages:docgen
  color: fbca04
- name: packages:formatters
  color: fbca04
- name: packages:next
  color: fbca04
- name: packages:proxy
  color: fbca04
- name: packages:proxy-container
  color: fbca04
- name: packages:rest
  color: fbca04
- name: packages:ui
  color: fbca04
- name: packages:util
  color: fbca04
- name: packages:voice
  color: fbca04
- name: packages:ws
  color: fbca04
- name: priority:high
  color: fc1423
- name: scope:backport
  color: ff8357
- name: scope:build
  color: ff8357
- name: scope:chore
  color: ff8357
- name: scope:ci
  color: ff8357
- name: scope:docs
  color: ff8357
- name: scope:feat
  color: ff8357
- name: scope:fix
  color: ff8357
- name: scope:perf
  color: ff8357
- name: scope:refactor
  color: ff8357
- name: scope:revert
  color: ff8357
- name: scope:style
  color: ff8357
- name: scope:test
  color: ff8357
- name: scope:types
  color: ff8357
- name: semver:major
  color: c10f47
- name: semver:minor
  color: e4f486
- name: semver:patch
  color: e8be8b
- name: type:application commands
  color: b6b1f9
- name: type:applications
  color: b6b1f9
- name: type:caching
  color: b6b1f9
- name: type:channel
  color: b6b1f9
- name: type:dependencies
  color: b6b1f9
- name: type:discord update
  color: b6b1f9
- name: type:gateway
  color: b6b1f9
- name: type:guild
  color: b6b1f9
- name: type:interactions
  color: b6b1f9
- name: type:invite
  color: b6b1f9
- name: type:monetization
  color: b6b1f9
- name: type:oauth2
  color: b6b1f9
- name: type:permissions
  color: b6b1f9
- name: type:poll
  color: b6b1f9
- name: type:rate limit
  color: b6b1f9
- name: type:regression
  color: b6b1f9
- name: type:role connections
  color: b6b1f9
- name: type:sharding
  color: b6b1f9
- name: type:stage instances
  color: b6b1f9
- name: type:sticker
  color: b6b1f9
- name: type:thread
  color: b6b1f9
- name: type:user
  color: b6b1f9
- name: type:voice
  color: b6b1f9
- name: type:webhook
  color: b6b1f9
- name: won't fix
  description: No work will be done towards this issue.
  color: cfd3d7
